# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/src/events/ruby_sample1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ruby_sample.requests.Add" do
    optional :user_uuid, :string, 1
    optional :correlation_id, :string, 2
    optional :uuid, :string, 3
    map :context, :string, :string, 4
    optional :data, :message, 5, "ruby_sample.requests.Add.Data"
    optional :reply_to, :string, 6
  end
  add_message "ruby_sample.requests.Add.Data" do
    optional :num1, :int64, 1
    optional :num2, :int64, 2
  end
end

module RubySample
  module Requests
    Add = Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_sample.requests.Add").msgclass
    Add::Data = Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_sample.requests.Add.Data").msgclass
  end
end
