# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/src/events/ruby_sample2.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ruby_sample.documents.Response" do
    optional :user_uuid, :string, 1
    optional :correlation_id, :string, 2
    optional :uuid, :string, 3
    map :context, :string, :string, 4
    optional :data, :message, 5, "ruby_sample.documents.Response.Data"
  end
  add_message "ruby_sample.documents.Response.Data" do
    optional :result, :int64, 1
  end
end

module RubySample
  module Documents
    Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_sample.documents.Response").msgclass
    Response::Data = Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_sample.documents.Response.Data").msgclass
  end
end
