# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/issue_time.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ruby_sample.commands.IssueTime" do
    optional :user_uuid, :string, 1
    optional :correlation_id, :string, 2
    optional :uuid, :string, 3
    map :context, :string, :string, 4
  end
end

module RubySample
  module Commands
    IssueTime = Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_sample.commands.IssueTime").msgclass
  end
end
